allowBuilds:
  '@swc/core': true
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.48.0'
  - '@cloudflare/workers-types@5.20260729.1'
  - miniflare@4.20260722.1
  - wrangler@4.115.0
